name: dump-event

on: [workflow_dispatch, pull_request_target]

jobs:
  dump-event:
    runs-on: ubuntu-latest
    steps:
    - name: event
      run: cat $GITHUB_EVENT_PATH
    - name: event
      run: echo $GITHUB_EVENT_NAME
